version: "3.5"
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ".:/config/www/"
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  db1:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer1:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8093:80
    environment:
      - PMA_ARBITRARY=1
