name: Build

on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: vm

    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Démarrage docker compose
        run: docker compose up -d

      - name: Init BDD
        run: docker compose exec db1 mysql -p"example" -h db1 -u root

      - name: Afficher la page web associée
        run: sleep 30 ; curl localhost

      - name: Stopper les conteneurs
        run: docker compose down
