name: Build

on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: linux,x64,gpu

    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Démarrage docker compose
        run: docker compose up

      - name: Init BDD
        run: mysql -p my_database InitDB.sql

      - name: Afficher la page web associée
        run: curl localhost

      - name: Stopper les conteneurs
        run: docker container kill $(docker ps | cut -d ' ' -f1 | tail -n +2 | paste -s)
