name: Build

on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: vm

    steps:
      - name: Stopper les conteneurs
        run: docker container kill $(docker ps | cut -d ' ' -f1 | tail -n +2 | paste -s)

      - name: Check out repo
        uses: actions/checkout@v1

      - name: Démarrage docker compose
        run: docker compose up

      - name: Init BDD
        run: docker compose exec db1 mysql -D my_database -p"example" -h db1 -u root

      - name: Afficher la page web associée
        run: curl localhost

      - name: Stopper les conteneurs
        run: docker container kill $(docker ps | cut -d ' ' -f1 | tail -n +2 | paste -s)
