name: Build

on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: vm

    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Démarrage docker compose
        run: docker compose up -d

      - name: Init BDD
        run: docker compose exec -T db1 mysql -pexample -u root < InitDB.sql

      - name: Afficher la page web associée
        run: docker compose exec nginx curl localhost

      - name: Stopper les conteneurs
        run: docker compose down
